laravel/routes/web.php
<?php

use App\Http\Controllers\GruposController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TrabalheConoscoController;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$grupos = Lang::get('routes.grupos');

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('en/groups/{slug}', [GruposController::class, 'index'])->name('grupos-en');
Route::get('es/grupos/{slug}', [GruposController::class, 'index'])->name('grupos-es');
Route::get('grupos/{slug}', [GruposController::class, 'index'])->name('grupos');

Route::post('contato', [HomeController::class, 'postContato'])->name('contato.post');

Route::get('en/work-with-us', [TrabalheConoscoController::class, 'index'])->name('trabalhe-conosco-en');
Route::get('es/trabaja-con-nosotros', [TrabalheConoscoController::class, 'index'])->name('trabalhe-conosco-es');
Route::get('trabalhe-conosco', [TrabalheConoscoController::class, 'index'])->name('trabalhe-conosco');
Route::post('trabalhe-conosco', [TrabalheConoscoController::class, 'post'])->name('trabalhe-conosco.post');
Route::get('trabalhe-conosco/{id}', [TrabalheConoscoController::class, 'openArquivoPDF'])->name('trabalhe-conosco.arquivo');

Route::post('aceite-de-cookies', [HomeController::class, 'postCookies'])->name('aceite-de-cookies.post');

// LANG
Route::get('lang/{lang}', function ($lang) {
    if (in_array($lang, ['pt', 'en', 'es'])) {
        Session::put('locale', $lang);
    }
    return back();
})->name('lang');

require __DIR__ . '/auth.php';

laravel/app/Models/Contato.php
<?php

namespace App\Models;

use App\Helpers\CropImage;
use App\Helpers\CropImageTinify;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Contato extends Model
{
    use HasFactory;
    use Notifiable;

    protected $table = 'contatos';

    protected $guarded = ['id'];

    public static function upload_imagem()
    {
        if (Configuracao::first()->tinify_key) {
            return CropImageTinify::make('imagem', [
                'width'  => null,
                'height' => null,
                'path'   => 'assets/img/contatos/'
            ]);
        } else {
            return CropImage::make('imagem', [
                'width'  => null,
                'height' => null,
                'path'   => 'assets/img/contatos/'
            ]);
        }
    }
}

laravel/app/Models/ContatoRecebido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContatoRecebido extends Model
{
    use HasFactory;

    protected $table = 'contatos_recebidos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/Painel/ContatosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatosRequest;
use App\Models\Contato;
use Illuminate\Http\Request;

class ContatosController extends Controller
{
    public function index()
    {
        $registro = Contato::first();

        return view('painel.contatos.edit', compact('registro'));
    }

    public function update(ContatosRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Contato::upload_imagem();

            $contato->update($input);

            return redirect()->route('contatos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/contatos/recebidos/index.blade.php
@extends('painel.layout.template')

@section('content')

@include('painel.layout.flash')

<legend class="mb-4">
    <h2 class="m-0">CONTATOS RECEBIDOS</h2>
</legend>

@if(!count($contatos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="contatos_recebidos">
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Nome</th>
                <th scope="col">E-mail</th>
                <th class="no-filter" scope="col"><i class="bi bi-gear-fill me-2"></th>
            </tr>
        </thead>

        <tbody>
            @foreach ($contatos as $contato)
            <tr class="@if(!$contato->lido)alert alert-warning @endif" id="{{ $contato->id }}">
                <td data-order="{{ $contato->created_at_order }}">{{ $contato->created_at }}</td>
                <td>{{ $contato->nome }}</td>
                <td class="d-flex flex-row align-items-center">
                    <button class="btn btn-dark btn-sm clipboard me-2" data-clipboard-text="{{ $contato->email }}">
                        <i class="bi bi-clipboard"></i>
                    </button>
                    {{ $contato->email }}
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                    'route' => ['contatos-recebidos.destroy', $contato->id],
                    'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm" role="group">
                        <a href="{{ route('contatos-recebidos.show', $contato->id ) }}" class="btn btn-primary btn-sm">
                            <i class="bi bi-chat-text-fill me-2"></i>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="bi bi-trash-fill me-2"></i>Excluir</button>

                        <a href="{{ route('contatos-recebidos.toggle', $contato->id) }}" class="btn btn-sm {{ ($contato->lido ? 'btn-warning' : 'btn-success') }}">
                            @if($contato->lido)
                            <i class="bi bi-arrow-repeat"></i>
                            @else
                            <i class="bi bi-check2-circle"></i>
                            @endif
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

@endif

@endsection

laravel/resources/views/painel/contatos/recebidos/show.blade.php
@extends('painel.layout.template')

@section('content')

<legend class="mb-4">
    <h2 class="m-0">CONTRATE CONOSCO</h2>
</legend>

<div class="mb-3 col-12">
    <label>Data</label>
    <div class="well">{{ $recebido->created_at }}</div>
</div>

<div class="mb-3 col-12">
    <label>Nome</label>
    <div class="well">{{ $recebido->nome }}</div>
</div>

<div class="mb-3 col-12">
    <label>E-mail</label>
    <div class="well">
        <button class="btn btn-dark btn-sm clipboard me-2" data-clipboard-text="{{ $recebido->email }}">
        <i class="bi bi-clipboard"></i>
        </button>
        {{ $recebido->email }}
    </div>
</div>

@if($recebido->telefone)
<div class="mb-3 col-12">
    <label>Telefone</label>
    <div class="well">{{ $recebido->telefone }}</div>
</div>
@endif

@if($recebido->empresa)
<div class="mb-3 col-12">
    <label>Empresa</label>
    <div class="well">{{ $recebido->empresa }}</div>
</div>
@endif

<div class="mb-3 col-12">
    <label>Mensagem</label>
    <div class="well-msg">{!! $recebido->mensagem !!}</div>
</div>


<div class="d-flex align-items-center mt-4">
    <a href="{{ route('contatos-recebidos.index') }}" class="btn btn-secondary btn-voltar">Voltar</a>
</div>

@stop